
-- SEED DATA AETERNA: pasal & sandi angka
insert into public.pasal (kode, tentang, denda, bulan, kategori) values
  ('1.1', 'Tidak Memiliki KTD / Tidak Membawa KTD', 2000, 5, 'Ringan'),
  ('1.2', 'Melakukan Penipuan Terhadap Warga', 2000, 5, 'Ringan'),
  ('1.3', 'Melakukan Pemalakan Terhadap Warga', 2000, 5, 'Ringan'),
  ('1.4', 'Memberi Informasi Palsu Kepada Petugas Kepolisian', 4000, 10, 'Ringan'),
  ('1.5', 'Pencemaran Nama Baik', 4000, 5, 'Ringan'),
  ('1.6', 'Pencemaran Nama Baik Kepada Instansi', 5000, 10, 'Ringan'),
  ('1.7', 'Menyalahgunakan Panggilan Hotline / Emergency Call', 5000, 5, 'Ringan'),
  ('1.8', 'Menghambat Penyelidikan', 3000, 5, 'Ringan'),
  ('1.9', 'Mabuk Di Tempat Umum', 2000, 5, 'Ringan'),
  ('1.0', 'Melakukan Perkelahian Di Tempat Umum', 3000, 5, 'Ringan'),
  ('2.0', 'Mengganggu Ketertiban Umum / Melakukan Provokasi', 4000, 5, 'Ringan'),
  ('2.1', 'Tidak Melengkapi Atribut Berkendara', 2000, 5, 'Ringan'),
  ('2.2', 'Memakai Hal Yang Tidak Senonoh Di Area Publik', 3000, 5, 'Ringan'),
  ('2.4', 'Melakukan Sifat Tidak Senonoh Di Area Publik / Keramaian', 3000, 5, 'Ringan'),
  ('2.5', 'Melakukan Aksi Demo Tanpa Izin', 4000, 10, 'Ringan'),
  ('2.6', 'Melakukan Aksi Anarkis Saat Melakukan Demo', 4000, 5, 'Ringan'),
  ('2.7', 'Menghalangi / Menghambat Petugas Instansi (Dalam Pengejaran)', 3000, 10, 'Ringan'),
  ('2.8', 'Mencuri Kendaraan Warga', 2000, 5, 'Ringan'),
  ('2.9', 'Mengkonsumsi Narkoba / Narkotika', 5000, 10, 'Ringan'),
  ('3.0', 'Penganiayaan / Pemukulan Terhadap Warga', 5000, 10, 'Sedang'),
  ('3.1', 'Melakukan Pembegalan Terhadap Warga', 5000, 10, 'Sedang'),
  ('3.3', 'Upaya Suap / Penyuapan Kepada Petugas', 6000, 10, 'Sedang'),
  ('3.4', 'Berada Di Zona Ilegal / Merah', 5000, 10, 'Sedang'),
  ('3.5', 'Menyalahgunakan Atribut Kepolisian', 4000, 10, 'Sedang'),
  ('3.6', 'Melakukan Perburuan Hewan Ilegal', 5000, 10, 'Sedang'),
  ('3.7', 'Membawa Minuman Beralkohol (Beer / Whiskey)', 5000, 10, 'Sedang'),
  ('3.8', 'Membawa Narkoba Dan Narkotika (Marijuana & Kanabis)', 6000, 15, 'Sedang'),
  ('3.9', 'Membawa Barang Ilegal (Kavlar, Linggis, Dan Kunci Letter T)', 6000, 5, 'Sedang'),
  ('3.9A', 'Membawa Hewan Yang Dilindungi (Hiu, Paus, Kadal, Dan Penyu)', 6000, 5, 'Sedang'),
  ('4.0', 'Kepemilikan Barang Ilegal (Uranium ACD & Uranium)', 6000, 5, 'Sedang'),
  ('4.1', 'Membawa Uang Merah $1 - $1.000', 6000, 5, 'Sedang'),
  ('4.2', 'Membawa Uang Merah $1.000 - $50.000', 8000, 5, 'Sedang'),
  ('4.4', 'Membawa Uang Merah $50.000 - $1.000.000', 9000, 15, 'Sedang'),
  ('4.5', 'Pencucian Uang Merah', 6000, 10, 'Sedang'),
  ('4.6', 'Pencurian Kendaraan Ilegal / Carsteal', 5000, 5, 'Sedang'),
  ('4.7', 'Smuggler / Penyelundupan Barang Ilegal', 5000, 10, 'Sedang'),
  ('4.8', 'Melakukan Proses Narkoba Dan Narkotika', 5000, 5, 'Sedang'),
  ('4.9', 'Melakukan Tindakan Kabur Dari Federal', 5000, 10, 'Sedang'),
  ('5.0', 'Pengedaran Terhadap Barang Ilegal (Kavlar, Marijuana, Kanabisa, Dsb.)', 10000, 15, 'Sedang'),
  ('5.1', 'Sengaja Atau Tidak Sengaja Berada Di TKP Peperangan', 6000, 5, 'Sedang'),
  ('5.2', 'Upaya Melakukan Perlawanan Terhadap Petugas', 8000, 10, 'Sedang'),
  ('5.3', 'Pengedaran Senjata Api Ilegal', 8000, 20, 'Berat'),
  ('5.4', 'Kepemilikan Senjata Api Ilegal (Handgun / Pistol)', 8000, 10, 'Berat'),
  ('5.5', 'Kepemilikan Senjata Api Ilegal (Laras Pendek / SMG)', 9000, 10, 'Berat'),
  ('5.6', 'Kepemilikan Senjata Api Ilegal (Laras Menengah / AK-47, Dsb.)', 10000, 15, 'Berat'),
  ('5.7', 'Kepemilikan Senjata Api Ilegal (Laras Panjang / Sniper)', 20000, 20, 'Berat'),
  ('5.8', 'Membuat / Merakit Senjata Api Ilegal', 9000, 5, 'Berat'),
  ('5.9', 'Tidak Memiliki Lisensi Senjata Api Resmi Kepolisian', 7000, 5, 'Berat'),
  ('6.0', 'Melakukan Tindakan Penyanderaan Kepada Warga', 7000, 10, 'Berat'),
  ('6.1', 'Melakukan Tindakan Penyanderaan Kepada Petugas Kepolisian', 8000, 15, 'Berat'),
  ('6.2', 'Melakukan Tindakan Penyanderaan Kepada Anggota Instansi', 8000, 15, 'Berat'),
  ('6.3', 'Upaya Pembunuhan Kepada Warga Maupun Petugas Kepolisian', 9000, 10, 'Berat'),
  ('6.4', 'Melakukan Penodongan Terhadap Warga', 8000, 10, 'Berat'),
  ('6.5', 'Melakukan Penodongan Terhadap Petugas Kepolisian', 8000, 15, 'Berat'),
  ('6.6', 'Melakukan Penembakan Kepada Warga', 8000, 15, 'Berat'),
  ('6.7', 'Melakukan Penembakan Kepada Petugas Kepolisian', 8000, 10, 'Berat'),
  ('6.8', 'Perampokan Warung Bersenjata', 8000, 15, 'Berat'),
  ('6.9', 'Peperangan Antar Kelompok', 8000, 10, 'Berat'),
  ('7.0', 'Tindakan Mencoba Menjadi Polisi Gadungan Atau Instansi Lainnya', 9000, 25, 'Berat'),
  ('7.1', 'Upaya Menghilangkan Barang Bukti', 7000, 10, 'Berat'),
  ('7.2', 'Upaya Penculikan Terhadap Warga Maupun Anggota Instansi', 10000, 15, 'Berat'),
  ('7.3', 'Melakukan Atau Mencoba Membantu Kriminalisme', 20000, 15, 'Berat'),
  ('7.4', 'Melakukan Perampokan Bank', 10000, 20, 'Berat'),
  ('7.5', 'Melakukan Perampokan Bank Besar', 15000, 25, 'Berat'),
  ('7.6', 'Perampokan Jawery', 9000, 15, 'Berat'),
  ('7.7', 'Melakukan Tindakan Korupsi Instansi', 0, 999, 'Persidangan')
on conflict (kode) do update set tentang = excluded.tentang, denda = excluded.denda, bulan = excluded.bulan, kategori = excluded.kategori, updated_at = now();

insert into public.ten_codes (kode, arti) values
  ('1-1', 'Hubungi per telepon'),
  ('1-4', 'Ingin bicara di udara / langsung'),
  ('2-1', 'Identitas Orang / Suspek'),
  ('2-2', 'Identitas Kendaraan'),
  ('3-1', 'Kasus Pembegalan'),
  ('3-1P', 'Kasus Perampokan'),
  ('3-2', 'Kasus Peperangan'),
  ('3-3', 'Kualitas suara jelek'),
  ('3-3L', 'Kecelakaan korban luka'),
  ('3-3M', 'Kecelakaan korban material'),
  ('3-3K', 'Kecelakaan korban meninggal'),
  ('3-3KA', 'Kecelakaan kereta api'),
  ('3-4-K', 'Kecelakaan, korban meninggal, pelaku melarikan diri'),
  ('4-4', 'Penerimaan jelek'),
  ('5-5', 'Penerimaan baik'),
  ('8-3', 'Visual hilang / lost visual / VSB'),
  ('8-4', 'Tersangka pengejaran turun dari kendaraan'),
  ('8-5', 'Unit GARUDA silahkan mengudara / berhenti mengudara'),
  ('8-6', 'Dimengerti'),
  ('8-7', 'Tersangka pengejaran ditemukan kembali'),
  ('8-8', 'Melamun'),
  ('8-9', 'Pesawat / helikopter mengalami kerusakan'),
  ('8-1-0', 'Izin off duty'),
  ('8-1-1', 'Izin on duty'),
  ('8-1-2', 'Selamat beristirahat'),
  ('8-1-3', 'Selamat bertugas'),
  ('10-1', 'Semua unit harap berkumpul di ...'),
  ('10-2', 'Menanyakan posisi / menginformasikan posisi'),
  ('10-3', 'Keluar radio'),
  ('10-4', 'Diterima / roger that'),
  ('10-5', 'Menghadap secara pribadi'),
  ('10-6', 'Saya sedang melakukan pekerjaan yang lain'),
  ('10-7', 'Terjadi kerusakan terhadap kendaraan'),
  ('10-8', 'Sedang dalam perjalanan menuju ...'),
  ('10-9', 'Mohon pesan diulang'),
  ('10-10', 'Mohon bantuan jemputan'),
  ('10-11', 'Kembali ke kantor polisi'),
  ('10-12', 'Mohon pindah frekuensi radio ke channel ...'),
  ('10-13', 'Anggota terlumpuhkan'),
  ('10-16', 'Mempercepat aktivitas'),
  ('10-51', 'Indikasi terjadi kejahatan'),
  ('10-61', 'Anggota dipersilahkan melumpuhkan suspek'),
  ('10-71', 'Terjadi penembakan terhadap anggota'),
  ('10-999', 'Peperangan besar / naikkan ke Siaga 1'),
  ('10-333', 'Penyanderaan anggota kepolisian / sesuai aturan penyanderaan'),
  ('10-000', 'Terorisme / Siaga 3'),
  ('10-200', 'Membutuhkan backup polisi di ...'),
  ('10-500', 'Membutuhkan provost di ...'),
  ('10-700', 'Membutuhkan medis di ...')
on conflict (kode) do update set arti = excluded.arti, updated_at = now();
